spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 12345678
  jpa:
    generate-ddl: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
