spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 12345678
  jpa:
    generate-ddl: true

jwt:
  secret: qwertyuiopasdfghjklzxcvbnm12345678900987654321qwerty
  lifetime: 30m
